MIDI/mathphreak_Learningbaby.jsfx

Since the Learningbaby can't see upcoming automation events, it has already scheduled the MIDI events for the old pattern when it receives the switch to the new pattern. Giving the Learningbaby direct control of the pattern transition allows it to handle that better.
This should have been possible with `slider_next_chg()`, but I tried using that to check for upcoming changes and it did not work reliably. (It properly anticipated some changes but did not properly anticipate others. All the changes were identical and properly aligned. It always succeeded or failed in the same places in my test project. I am confused.)

Improve Learningbaby pattern automation

---

MIDI/urtzurd_MIDI Glissando.jsfx

Hi!
Lately I've been playing around with the idea of creating a MIDI glissando effect in Reaper, inspired by that in the almighty CS80 synthesizer. This is my first version coded as a JS effect.
The idea behind the effect is that when you play a note, it will slide from the previous one, but in semitones steps. It allows to use polyphony, and the algorithm I implemented favors sliding from the previous last note, so a melody can be played in a predictable way while holding some chords.
Hope you find it useful and you're willing to include it in the repo.
Cheers!

MIDI Glissando - First version release

---

Misc/brumbear_LiveBeatRepeater.jsfx

1.02: Added Features
- Continuous Loop Length Change Slider. Map this one to a rotary encoder in relative mode. When used the loop length transitions will happen immediately while repeat mode is on. When repeat mode switches back to off the plugin automatically goes back to stepped mode.

Release LiveBeatRepeater v1.02

---

MIDI/cfillion_MIDI note length control.jsfx

Decrease maximum visible range of beats sliders to 8 beats (was 255)
Fix embarrassingly wrong calculation of beats to seconds
Improve behavior when the minimum beats slider > maximum beats and vice versa

Release MIDI note length control v1.0.2

---

MIDI/TJA_MIDI Performer2.jsfx

v0.5.1
- Range all sliders from 0 to gain compatibility with ReaLearn relative mode (Transpose, Out Channel and Max Note sliders now work)
v0.5
- Renamed to MIDI Performer2 because presets will not be compatible - too many changes under the hood
- Variable no. of rows - up to 32 rows
- Rows can be always enabled (∀)
- Program Changes can be sent on preset load and Row # change (edit @init to enable PC by default & on project load)
- Add output monitor
- Generate 6 CCs per row (edit @init to change which CCs)
- Reshuffle columns (out is now last)
- Fixed Touchpad value scrolling
- Automation: Sliders update to top 4 selected rows

Release MIDI Performer2 v0.5.1

---

MIDI/TJA_MIDI Performer2.jsfx

- Split multiple keyzones to lanes instead of overlapping
- Right Click on number sliders to revert to default value (draggable)
- Add hanging prevention to input parameters (## is now the only parameter that will leave notes hanging)

Release MIDI Performer2 v0.5.3

---

Utility/mschnell_MIDI Display Patch Name.jsfx

allow for bank no > 7
Explicitly disallow more than 1024 patch names (due to limitation of JSFX/EEL)
Bug fixes

Release MIDI Display Patch Name v1.1

---

MIDI/talagan_MIDI CC Mapper X.jsfx

Fix : HighRes midi velocity was not properly handled for MSB 1, LSB 0.
Fix : Highres midi velocity LSB was not sent on the proper CC (#88).
Added a "pen" button to trigger pen mode, to avoid accidental clicks on the curve
Added channel routing options for notes and ccs.
Added firewall option for unrouted notes.
Since red keys may now be kept due to channel re-routing, added an option to select what keys are transposed (All/Green/Red)
Since red keys may now be kept due to channel re-routing, added an option to select what keys are affected by the velocity control (All/Green/Red)
Added curve mih/max behaviours : the user can now set some min/max limits on the curve, so that the curve is clamped between those bounds. Predefined curves will be adapted to that range and pen drawing will be …

Release MIDI CC Mapper X v3.3

---

MIDI/talagan_MIDI CC Mapper X.jsfx

I forgot to update the version number displayed in the bottom bar, as remarked on the forum. Sorry for the extra commit!

MIDI CC Mapper X 3.6 -> 3.6 (amend) : hotfix for version display in the bottom bar

---

Misc/brumbear_LiveBeatRepeater.jsfx

Added Features
- Additional Loop Lengths ("Tripplets" and as short as 1/128)
- Logarithmic scaling of continuous loop length slider

Release LiveBeatRepeater v1.03

---

Misc/brumbear_LiveBeatRepeater.jsfx

- Sample accurate time sync: Loop Start at next beat or bar now sample accurate in time
- Fade in: Loop starts with fade-in on interpolated slope from loop end to reduce audio artefacts

Release LiveBeatRepeater v1.04

---

Misc/brumbear_LiveBeatRepeater.jsfx

- 3 different loop fade algorithms selectable by user
- Updated Fx routing options
- Added loop start, loop end and playhead indicators (cannot be manipulated yet)
- Improve memory management
- Fixed bug during loop fade out when reversing

Release LiveBeatRepeater v1.12

---

Misc/brumbear_LiveBeatRepeater.jsfx

- Added Slice Pattern Sequencer*
- Added Loop Freeze/Recall feature*
- Added new routing option
- Added vertical zoom slider for waveform
- Fixed wrong beat/bar length calculations for certain time signatures (Reaper's tempo is actually QPM, not BPM)
- Fixed slice start calculation when changing Slice Start Pos slider (was off by 1 sample)
*Note: Switching Pattern Sequencer on/off and Freeze/Recall can be automated just like other non hidden sliders

Release LiveBeatRepeater v1.30

---

Misc/brumbear_LiveBeatRepeater.jsfx

- Added multiple MIDI control options for grid based slicer
- Added GUI mouse controls for manipulation of Slice Start/End and Slice Move (new).
- Allow manipulation of Slice Start/End while pattern is playing and terminate pattern mode immediately
- Added GUI indicator to show if plugin is in QUANTIZE mode
- Improved behavior when length transitions are set to "At Next Beat"

Release LiveBeatRepeater v1.50

---

Utility/CoreyScogin_AutoMixer.jsfx

Currently, the track average is computed by adding the channels. This works most of the time, because the signal in the channels are similar (most often they’re mono, really), which is probably why this bug wasn’t noticed until now. But there are cases in which the channels are out-of-phase, and adding them together will result in destructive interference. Still, the channels are producing sound, and shouldn’t be muted by the automixer.
The solution is to add the channels **after squaring them**. This gets rid of the negative values.
In other words: we add up the channels on the power domain, not the amplitude domain.
See the example project on this Pull Request for a pathological case in which one of the aumixed microphones is a stereo signal in which the left and right channels are …

Fix computation of track average in Automixer

---

MIDI/talagan_MIDI CC Mapper X.jsfx

Updating MIDI CC Mapper X from 4.1 to 4.2. 
Changelog :
- Default value for keyboard ranges transposition is now ON instead of OFF (it feels more logical in the main flow)
- Added pass through option per control to keep original events and allow event duplication

MIDI CC Mapper X 4.1 -> 4.2

---

MIDI/erantalmor_MIDI Rhythm Trainer.jsfx

>> Improved Swing and Phase handling:
* Double click to reset
* Added "angle" value alongside decimal fraction
* Control-drag in jumps of 30 degrees (==1/12 == 0.08333)
* Swing range expanded to -0.92 => +0.92 (-330 => 330 degress)
>> Fixed a glitch playing double clicks when enabling the click.
>> Mouse wheel also control click on/off.

Release MIDI Rhythm Trainer v1.02

---

MIDI/erantalmor_MIDI Rhythm Trainer.jsfx

* Fixed an critical bug preventing changing swing/phase on Lanes 2/3/4
* Renamed slider "Number of Lanes" to "Lanes"

Release MIDI Rhythm Trainer v1.03

---

MIDI/erantalmor_MIDI Rhythm Trainer.jsfx

Added per-lane "probability density" curves (1.10)!
These show you where you have been hitting the pattern, and gives a picture of how accurate you are on specific locations (early, late, variance,...).
Fixes:
Issues with click and looping.
Fixed some minor graphical issues.
Junk character when  printing phase/swing angle (fix of 1.11)

Release MIDI Rhythm Trainer v1.11

---

MIDI/erantalmor_MIDI Rhythm Trainer.jsfx

Save state of training graph and probability curves between "Play"s.
Easier setting of mask by right mouse button drag over grid lines.

Release MIDI Rhythm Trainer v1.13

---

MIDI/TJA_MIDI Performer2.jsfx

- More detailed input monitor
- Aftertouch and Channel Pressure support - filtered with CC's
- Slider compatibility: Host parameter ranges play nicer with scrollwheel, Automap, MIDI learn, ReaLearn, OSC, CSurf, etc..
- GUI compatibility: defaults to fixed size + settings for size control. More Linux friendly?
- # Presets
- Global transpose
- Default deviation notification
0.6.01
-fix global transpose preset bug

Release MIDI Performer2 v0.6.01

---

Distortion/rcjach_RCInflator.jsfx

This version clones the behavior of the Sonnox Oxford Inflator in every aspect but "bandsplit" mode.

Change desc: to distinguish from original

---

Utility/mschnell_Dual Time adjustment.jsfx

Fix: Loading the plugin with Dual mode resulted in equal delay for both channels due to some weird way Reaper calls @slider multiple times

Release Dual Time adjustment +/- Delay v2.1

---

MIDI/juan_r_MIDI Fret and Pick.jsfx

1.00  initial release
1.01  clean code, add idle option: mixed recycle+octave
1.02  improved "about" docs
1.03  added options to make fretting notes play immediately

Release MIDI Fret and Pick v1.03

---

Distortion/RCInflator2_Ideal.jsfx
Distortion/RCInflator2_Oxford.jsfx

Based on code presented at https://forum.cockos.com/showpost.php?p=2581992&postcount=201.
Both JSFX are incompatible with the original RCInflator (Oxford Edition) due to changed order of sliders so are therefore added alongside. The original continues to be useful for users not requiring a band split option.

Add RCInflator v2 Oxford and Ideal Editions

---

MIDI/talagan_MIDI CC Mapper X.jsfx

Update for MIDI CC Mapper X v4.3 > v4.3.1. Changelog : 
- Added info notice in AfterTouch widgets to warn about Channel Pressure virtual CC#128

MIDI CC Mapper X 4.3 > 4.3.1

---

Utility/zenomod_VU Meter (ZenoMOD).jsfx

fix: meter output slider scaling adjusted (ATTENTION: not backwards compatible with parameter modulation in old projects!)
fix: increase display probability of preferences button in case meter options page is open and bottom bar is not visible (edge case).
fix: bottom bar tooltips are now displayed at any possible UI scaling.
Channel labels now reflect selected channel mode (dagamusik).
Reduced visibility of channel labels in case tooltip text position is equal to that of channel labels (to improve readability of tooltips).
Add slider_automate() function for meter output sliders to enable meter output automations.
Add hidden slider for tooltip button to permanently disable tooltips by saving a plugin preset.
Add right-click popup menu for UI style button.
Add right-click popup menu for …

Release VU Meter (ZenoMOD) v1.7.2

---

MIDI/talagan_MIDI CC Mapper X.jsfx

This is an update for MIDI CC Mapper X, from V4.3 to V5.0. Changelog : 
- Added curve morphing with automation for each control
- Added auto-emit MIDI events for automated morphed curves
- Relaxed transposition constraints on octavas (allow +/- 8 instead of +/- 2)
- Added call to freembuf to reduce memory footprint

MIDI CC Mapper X V4.3 > V5.0

---

MIDI/talagan_MIDI CC Mapper X.jsfx

Update for MIDI CC Mapper X 5.0 to 5.1. Changelog : 
- Feature : Added conditional channel dropping/routing for CCs, CP, Pitch Bend and Poly AT.
- Hot fix : Pitch Bend : Display limits between 0..8191 instead of 0..127
- Bug fix : Poly AT widget disabled but with passthrough on would produce unnecessary events
- Hot fix : the drawing of the result curve when morphing would glitch on the first point (one frame late)

MIDI CC Mapper X 5.0 > 5.1

---

MIDI/erantalmor_MIDI Rhythm Trainer.jsfx

* Adjustable latency compensation for working with upstream audio-to-midi plugins (e.g. guitar / drums).
* Error bound is set in absolute time (ms) instead of relative time, promoting better tracking across different tempos and divisions.
* Current beat is highlighted, shrinking towards next beat.
* Fixed minor memory overwrite.

Release MIDI Rhythm Trainer v1.21

---

MIDI/talagan_MIDI CC Mapper X.jsfx
MIDI/talagan_MIDI CC Mapper X/lib.txt

Release commit for MIDI CC Mapper X 5.3. Changelog : 
- Bug Fix : Note OFF velocities are not forced to zero anymore, but left intact
- Feature : Made the circ family parametric, with varying radius
- Feature : Added channel info on the keyboard indicator when playing MIDI notes
- Feature : Added x,y position when free hand drawing
- Feature : Added xmirror, ymirror curve buttons
- Cosmetics : Reworked drawing toolbar buttons with xpm icons (pen, smooth, copy, paste)
- Cosmetics : Added tooltips on drawing toolbar buttons
- Cosmetics : Added pen mouse cursor when free hand drawing

Update MIDI CC Mapper X 5.2 > 5.3

---

Synth/tilr_JSWavesynth.jsfx

Release JSWavesynth v1.1.1

---

Synth/tilr_JSAdditiv.jsfx

Release JSAdditiv v1.1.1

---

MIDI/talagan_MIDI CC Mapper X.jsfx

This is a minor update for MIDI CC Mapper X. Changelog : 
- Bug Fix : Note OFF events with non-zero velocities should make keypress feedback indicator disappear

Update MIDI CC Mapper X 5.3 > 5.3.1

---

MIDI/erantalmor_MIDI Rhythm Trainer.jsfx

Version 1.22:
* Added margins on the left and right of the grid to improve the cyclic presentation of the data around the edges
(event, histograms, grid lines).
* Improved beat visibility by adding a beat ruler with alternating colors, and making the beat lines more pronounced.
* Now the phase can be dragged negatively, up to -360 degress. This is useful with working with the "copied" 1st grid line 
at the right margin.
* Mellowed down error rate update to be less jumpy.
* Minor color updates.

Release MIDI Rhythm Trainer v1.22

---

MIDI/TJA_MIDI Performer2.jsfx

- Filter sustain pedal with note filter

Release MIDI Performer2 v0.6.5

---

MIDI/talagan_MIDI Note Remapper.jsfx

Small update for "MIDI Note Remapper".

Update MIDI Note Remapper v0.4 > v0.5

---

MIDI/talagan_MIDI Note Remapper.jsfx

Small update for MIDI Note Remapper. Changelog : 
- Poly AT messages are now remapped for coherency
- [Bug Fix] Mapping was not applied to notes defining only a remapping for the off velocity

Update MIDI Note Remapper v0.5 > v0.6

---

MIDI/talagan_MIDI Force Notes to Range.jsfx

Small JSFX to force MIDI notes to stay within a defined range by adding octavi (when too low) or removing octavi (when too high) - as requested on the forum.

Release MIDI Force Notes to Range v0.5 (Initial Release)

---

MIDI/talagan_MIDI Delay X.jsfx

Small update for MIDI Delay X, with a behaviour change/fix.

Update MIDI Delay X v0.3 > v0.4

---

MIDI/gofer_Poly Aftertouch Converter.jsfx

Add Poly aftertouch message output (going through value transform functions)

Release Poly Aftertouch Converter v1.0.1

---

MIDI/mschnell_Note On Delay Tool.jsfx

Release Note On Delay Tool v1.1

---

MIDI/talagan_MIDI Multi Channel Pre-Delay Live Flagger.jsfx
MIDI/talagan_MIDI Multi Channel Pre-Delay.jsfx

Update for MIDI Multi Channel Pre-Delay. Changelog : 
- [Feature] Added "Max Delay" option, in case 1 second is not sufficient
- [Feature] Added "Don't delay live events" option, using companion JSFX
- [Prereq]  Added companion JSFX for option above

Update MIDI Multi Channel Pre-Delay v0.5 > v0.6

---

Distortion/reincore_MegaGrit.jsfx

- Fixed a critical bug where the mid-band signal was always silent.
- Added 'Envelope Smoothness' slider for direct control over the modulation's character.
- Replaced the high-band clipper with a smoother soft-clip distortion.
- Added input clamping for improved stability at high gain.
- Lowered the default 'Input Drive' for a better experience.
_* Special thanks to ashcat_lt for the feedback!_

Update reincore_MegaGrit.jsfx to v2.0

---

MIDI/tomaszpio_AKAI APC mini grid toggle.jsfx

Release AKAI APC mini grid toggle v1.0.0
